//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyLogger.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyLogger.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon controller {
            get {
                object obj = ResourceManager.GetObject("controller", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboardmouse {
            get {
                object obj = ResourceManager.GetObject("keyboardmouse", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboardmouse2 {
            get {
                object obj = ResourceManager.GetObject("keyboardmouse2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mouse {
            get {
                object obj = ResourceManager.GetObject("mouse", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Mouse_Keyboard {
            get {
                object obj = ResourceManager.GetObject("Mouse_Keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap network_cn {
            get {
                object obj = ResourceManager.GetObject("network_cn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap network_dc {
            get {
                object obj = ResourceManager.GetObject("network_dc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of this program running already!.
        /// </summary>
        internal static string Program_Main_Instance_Limit {
            get {
                return ResourceManager.GetString("Program_Main_Instance_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid IP Adress.
        /// </summary>
        internal static string StartForm_button_Connect_Click_Not_a_valid_IP_Adress {
            get {
                return ResourceManager.GetString("StartForm_button_Connect_Click_Not_a_valid_IP_Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string StartForm_Button_Connect_Connect {
            get {
                return ResourceManager.GetString("StartForm_Button_Connect_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting ....
        /// </summary>
        internal static string StartForm_Button_Connect_Connecting {
            get {
                return ResourceManager.GetString("StartForm_Button_Connect_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed!.
        /// </summary>
        internal static string StartForm_NetworkClient_NetworkEvent_Connection_failed {
            get {
                return ResourceManager.GetString("StartForm_NetworkClient_NetworkEvent_Connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active network detected!.
        /// </summary>
        internal static string StartForm_StartForm_No_active_network_detected {
            get {
                return ResourceManager.GetString("StartForm_StartForm_No_active_network_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string StartFormMetro_MetroButton_Connect_Connect {
            get {
                return ResourceManager.GetString("StartFormMetro_MetroButton_Connect_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string StartFormMetro_MetroButton_Connect_Disconnect {
            get {
                return ResourceManager.GetString("StartFormMetro_MetroButton_Connect_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string StartFormMetro_MetroLabel_Network_Connected {
            get {
                return ResourceManager.GetString("StartFormMetro_MetroLabel_Network_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string StartFormMetro_MetroLabel_Network_Disconnected {
            get {
                return ResourceManager.GetString("StartFormMetro_MetroLabel_Network_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying.
        /// </summary>
        internal static string StartFormMetro_MetroLabel_Network_Trying {
            get {
                return ResourceManager.GetString("StartFormMetro_MetroLabel_Network_Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active network detected! Please restart the application..
        /// </summary>
        internal static string StartFormMetro_StartFormMetro_No_active_network_detected {
            get {
                return ResourceManager.GetString("StartFormMetro_StartFormMetro_No_active_network_detected", resourceCulture);
            }
        }
    }
}
