//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyLogger.Display.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyLogger.Display.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon controller {
            get {
                object obj = ResourceManager.GetObject("controller", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard_German {
            get {
                object obj = ResourceManager.GetObject("Keyboard_German", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Keyboard xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;KeyList&gt;
        ///    &lt;KeyRectangle&gt;
        ///      &lt;Key&gt;Oem1&lt;/Key&gt;
        ///      &lt;Mapping&gt;
        ///        &lt;Location&gt;
        ///          &lt;X&gt;569&lt;/X&gt;
        ///          &lt;Y&gt;125&lt;/Y&gt;
        ///        &lt;/Location&gt;
        ///        &lt;Size&gt;
        ///          &lt;Width&gt;45&lt;/Width&gt;
        ///          &lt;Height&gt;45&lt;/Height&gt;
        ///        &lt;/Size&gt;
        ///        &lt;X&gt;569&lt;/X&gt;
        ///        &lt;Y&gt;125&lt;/Y&gt;
        ///        &lt;Width&gt;45&lt;/Width&gt;
        ///        &lt;Height&gt;45&lt;/Height&gt;
        ///      &lt;/Mappin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardMapping {
            get {
                return ResourceManager.GetString("KeyboardMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboardmouse {
            get {
                object obj = ResourceManager.GetObject("keyboardmouse", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon keyboardmouse2 {
            get {
                object obj = ResourceManager.GetObject("keyboardmouse2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mouse {
            get {
                object obj = ResourceManager.GetObject("Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Mouse_Keyboard {
            get {
                object obj = ResourceManager.GetObject("Mouse_Keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mouse1 {
            get {
                object obj = ResourceManager.GetObject("mouse1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Mouse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ButtonList&gt;
        ///    &lt;ButtonPolygon&gt;
        ///      &lt;Button&gt;None&lt;/Button&gt;
        ///      &lt;ListPoint&gt;
        ///        &lt;Point&gt;
        ///          &lt;X&gt;0&lt;/X&gt;
        ///          &lt;Y&gt;0&lt;/Y&gt;
        ///        &lt;/Point&gt;
        ///        &lt;Point&gt;
        ///          &lt;X&gt;1&lt;/X&gt;
        ///          &lt;Y&gt;1&lt;/Y&gt;
        ///        &lt;/Point&gt;
        ///        &lt;Point&gt;
        ///          &lt;X&gt;1&lt;/X&gt;
        ///          &lt;Y&gt;0&lt;/Y&gt;
        ///        &lt;/Point&gt;
        ///      &lt;/ListPoint&gt;
        ///    &lt;/ButtonPolygon&gt;
        ///    &lt;ButtonP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MouseMapping {
            get {
                return ResourceManager.GetString("MouseMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller .
        /// </summary>
        internal static string Overview_Controller {
            get {
                return ResourceManager.GetString("Overview_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard .
        /// </summary>
        internal static string Overview_Keyboard {
            get {
                return ResourceManager.GetString("Overview_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse .
        /// </summary>
        internal static string Overview_Mouse {
            get {
                return ResourceManager.GetString("Overview_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active network connection detected!.
        /// </summary>
        internal static string Overview_No_active_network_connection_detected {
            get {
                return ResourceManager.GetString("Overview_No_active_network_connection_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XBox_Controller {
            get {
                object obj = ResourceManager.GetObject("XBox_Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
